- README.md
Added following sites to video list:
Coverr
Distill
Pexels Videos
Vidsplay
> Add: Added sites to video list

- README.md
I think there is no point of exposing the URL and without it the list is much clearer..
> Refactored list

- README.md
and also sorted by name the main list :)
> Added CSS3 Patterns Gallery

- README.md
Maybe we could add more comments, but this one is special since it's a search engine..
> Added a comment about libre

- README.md
> New CC0-license item

- README.md
Stocksy.com is a paid royalty-free, Cliché-free stock photo site with an excellent UI
> Add Stocksy

- README.md
It's capitalised everywhere http://glyphicons.com/license/
> Fixed GLYPHICONS name

- README.md
Here is their CC0-page https://stocksnap.io/license
> Added stocksnap

- README.md
> Ico Moon > IcoMoon

- README.md
Fixes #29 
Maybe using the :copyright: for the licenses..
> Added Sounds & Music

- README.md
The font team at Debian have a page set up with all of the fonts in sid listed with previews and download links. The fonts here are guaranteed to be free software under the [DFSG](https://www.debian.org/social_contract#guidelines).
> add debian fonts

- README.md
Added free-images.cc to the list.
> Added free-images.cc to CC0 image libraries

- README.md
I followed the format suggested in issue #17.
> Add NASA JPL's gallery to the attribution-required list

- README.md
Add description and links to Freepik and Flaticon.
> Add Freepik and Flaticon

- README.md
Bfxr is an easy way to make sounds for games. I think it would make a great addition to the list!
> Added Bfxr

- README.md
It's a new stock photography site with some really good quality stock photos of India, most of them taken by professionals. All photos are licensed under CC0, and they have one new submission everyday.
> Adding PickleJar.in

- README.md
There are bunch of Libre typeface projects in [Impallari](http://www.impallari.com/). Wanna add on awesome-stock-resources' ‘Fonts’ category.
> Add: Impallari on 'Fonts' category

- README.md
Add Iconfinder, my favorite source for icons. Note that the copyright depends on the icon, you can see it pretty clear under every icon after you clicked on it.
> Add Iconfinder

- README.md
Royalty free music powered by machine learning
> Add Jukedeck

- .travis.yml
- README.md
This pull request addresses Travis issues
> Update Travis white list

- .travis.yml
- README.md
This pull request fixes Travis issues
> Travis Update 

- README.md
> materialui.co: not https

- README.md
Their license is in the sidebar of their site ( http://streetwill.co ); scroll to the bottom and click on "free to use any way you want" to go to the cc0 page.
> Adding Streetwill to cc0

- README.md
[Creative Commons Zero license](https://www.stockified.com/license-and-terms/)
> All photos published on Stockified are licensed under Creative Commons Zero which means you can copy, modify, distribute and use the photos for free, including commercial purposes, without asking permission from or providing attribution to the photographer or Stockified, but it is always appreciated 😉
Also removed links that don't work anymore and fixed errors from Travis-CI.
> Add Stockified

- README.md
added freevectors.net to the Vector Graphics section
> added frevectors.net to the Vector Graphics section

- README.md
added compfight.com to Custom License / Usage section
> added compfight.com to Custom License / Usage section

- README.md
Added Videezy to the Videos Section
> added videezy to the Videos section

- README.md
added vecteezy.com to the Vector Graphics section
> added vecteezy.com to the Vector Graphics section

- README.md
added Themezy to the HTML Templates section
> added Themezy to the HTML Templates section

- README.md
> Update Photo Collections link

- README.md
Added resource to Aggregated Content section - https://reviewsquirrel.com/best-low-poly-generators/
> Added resource to Aggregated Content section

- README.md
Adding Standart.io a clean crisp Icon Font
> Adding Standart.io

- README.md
Game-icons.net is a quite large (3k+) set of vector icons
that are most suitable for usage in video games. Licensed under CC-BY 3,0
> Add Game-icons.net

- README.md
> GLYPHICONS no longer offers any "free set"

- README.md
Heya, 
The build for #177 failed because a site is no longer active. This PR should remove the site from the list allowing us to have passing builds again 🎉 
Take care,
> Remove photocollections.io

- README.md
As seen on [Hackernews](https://news.ycombinator.com/item?id=19031222) 🎉
> Add WOWA Music

- README.md
Adding Wesaturate.com to the list of CC0 image links.
> Adding Wesaturate

- README.md
Also added "Textures" category because this website didn't belong anywhere.
> Add TextureHaven

- README.md
Heya, 👋 
I found this awesome vector based illustrations site you can use for any commercial or non-commercial projects. It would be cool to share this with the rest of the world. 🎉
> Add unDraw.co

- README.md
The URL to Beautiful Web Type has changed. The previous domain was purchased by a spammer who is using it to link to their essay writing services. The new URL also contains a much improved version of the project. Thanks!
> Update URL to Beautiful Web Type

- README.md
Hero Patterns is a collection of free CC Attribution 4.0 repeatable 
SVG background patterns for use on web projects.
> Add Hero Patterns

- README.md
Sorry - only supposed to submit one at a time - my bad!
- Link to Biodiversity Heritage Library Flickr collection.
- Link to Pathlove icons.
Also stripped some trailing whitespaces.
> Add Biodiversity Heritage Library Flickr collection

- README.md
Added VYOO a collection of beautiful stock vertical videos
> Added VYOO

- README.md
> Add Heroicons

- README.md
Added Reshot custom license photography source
> Added Reshot

- README.md
Added Coolhue 2.0 custom gradients and swatches
> Added Coolhue

- README.md
Added To icon. An SVG icon collection
> Added To icon

- README.md
Added a SVG based icon library
> Added Simple Icons

- README.md
Added IconStore a collection of SVG & sourcefiles icons
> Added IconStore

- README.md
https://mixkit.co/free-stock-video/ - High-quality stock videos that are completely free.
> Add Mixkit

- README.md
Hey @neutraltone 
just removing an project which doesn't exist anymore.
Cheers!
> Removing project

- README.md
Pixabay has a video section so I have added it there in addition to the Photography section.
> Add Pixabay to video section

- README.md
> Add Iconoir

- README.md
https://github.com/microsoft/fluentui-system-icons
> Add Microsoft fluent icons

- README.md
See https://khushmeen.com/icons.html.
> Add Doodle Icons

- README.md
See https://bioicons.com/.
Although Bioicons are branded as icons, I think they better fit into the "Illustration"-section.
CC @duerrsimon.
> Add Bioicons

- README.md
https://www.iconshock.com/freeicons/
> We have collected and tagged all the icons from absolutely all the open source icon collections available. 100k icons for you to free download :)
> Add Free Icons

- README.md
https://humbleicons.com/
:octocat:
> Add Humbleicons

- README.md
> Add "Free Icons"

- README.md
Added Branition Colors - Hand-curated collection of color pallets best fitted for branding.
> Added in Color Section

- README.md
https://icons.getbootstrap.com/
> Add "Bootstrap Icons"

- README.md
> Add "Lucide" icons

- README.md
> Add "Unicorn" icons

- README.md
> Add BlendIcons

- README.md
> Add Tunetank

- README.md
> Add "Flowbite" icons

- README.md
> Add "Iconhunt"

- README.md
https://atlasicons.vectopus.com/
> Add "Atlas Icons"
